/**
 * The model-facing announcement: what the 画码 board is, where scenes live,
 * how to cooperate (draw → iterate → generate pages).
 * @module dsh-draw2code/host/guidance
 */

/** Order of the announcement section within the tool-guidance band. */
export const SECTION_ORDER = 220

export const DRAW2CODE_GUIDANCE = [
  '本机已安装 dsh-draw2code 插件（画码 · Draw2Code）：DSH Web GUI 右侧 better-sidebar 边栏里的「画码」标签页（Excalidraw 画板，从 + 菜单或标签栏打开）。新项目工作流：用户表达“我想做/创建/开发一个新的……”时，先调用 draw2code_create action=start 进入 choice-first grilling，不能直接调用 draw2code_update；idea 必须忠实传入用户原话，不要先替用户扩写需求。每次返回 question 时，优先调用宿主 ask_user_question，以一个问题和全部结构化 options 让用户直接选择，必须保留“还没想好”和“其他”等选项，禁止截断选项或只让用户在输入框里手动输入；收到选择后把 label 映射回 option id，再调用 draw2code_create action=answer。只有宿主没有 ask_user_question 时，才退化为编号文本。用户说“继续之前的项目”但没有明确项目时，先调用 draw2code_create action=list，让用户选择草稿；明确项目后用 action=resume。用户确认 ready 的项目简报后，调用 draw2code_create action=confirm；只有拿到 nextAction=draw2code_update 和 boardName 后，才调用 draw2code_update 把第一轮核心原型画到这个新画板。已有项目工作流：用户直接在画板上拖改、删模块、加文案；你先用 draw2code_read 读取最新画板，再继续 draw2code_update 迭代；打磨好后用户说"根据画板生成页面"，你调用 draw2code_generate 拿到范围与约束后生成前端页面。',
  'draw2code_create 的 grilling SOP：依次补齐目标端、核心用户、核心目标、最重要的用户流程、首版核心模块、首轮核心页面；用户原话已经明确 App/Web/小程序时工具会预填并跳过目标端，禁止重复追问。平台/用户/目标/流程默认单选，模块和页面可多选。候选选项是帮助思考的脚手架，不限制用户：用户可以选“其他”并补充文字；自由文字由工具直接记录，ready 简报是唯一统一确认点，不要逐项复述原话再问“这样理解对吗”。“还没想好”可以跳过，但要作为显式待定项或默认假设记录。项目名只保留核心产品名，不要把“类似、风格、通过、功能描述”等整句塞进项目名或画板名；APP/Web/小程序/平台/系统等完整产品类型不能再追加“工具”。draw2code_update 绘制时，页面必须使用 frame，组件必须有清晰的 text 标签或语义 customData；不要把所有控件画成无标签的方框。必须逐页落实 brief.pageMockData：列表、雷达、聊天、图表、详情和状态组件至少放入 3 条具有真实语义的示例内容，包含理解产品所需的对象、数值、状态、时间或消息；禁止用空白方框、Lorem ipsum、“用户A”“标题”“内容”等无意义占位符代替。完整页面 frame 设置 customData.role=prototype-page 和 customData.mockDataMin（通常为 3），每条承载 mock 数据的可见 text 设置 customData.role=mock-data；draw2code_update 会据此执行内容可读性门禁。优先表达按钮、输入框、Tab、列表、卡片、导航和箭头等产品语义，低保真只降低视觉精度，不降低信息可读性。具体几何规则：页面内元素用 frameId 指向页面 frame，绝不能用 containerId 表示页面归属；containerId 只用于绑定 rectangle/diamond/ellipse 的唯一文字标签。若 Agent 误把 text.containerId 指向 frame，draw2code_update 会自动修复为 frameId，避免 mock 数据写进 JSON 却在画布上不可见。多行或预计换行的 text 必须给足 height；按钮、卡片和输入框的外框不能携带 text，必须用独立 text 子元素；一个外框只有一个标签时给 text 设置 containerId，draw2code_update 会自动补齐外框的 boundElements，保证首次渲染可见；一个外框有多个标签（例如底部导航）时不要把多个 text 绑定到同一 containerId，可用相同 groupIds 表达分组。移动端 frame 先预留底部安全区，底部导航用 customData.role=bottom-navigation 的矩形 shell 加独立标签，贴近 frame 底部且不要用一行普通文字代替；组件不要被 frame 边界截断。draw2code_update 会在写盘前执行 layout-invalid 预检，失败时按错误信息修正并重试，不要把失败结果报告为已画好。原型阶段不询问品牌色、字体、圆角、阴影、3D/2D、扁平/拟物等视觉风格；但原型也不能只有黑白空框，应使用克制的语义色帮助扫读：主要操作/选中态用 primary，完成/正向状态用 success，提醒用 warning，逾期/错误用 danger，次级分类可用 info，弱信息用 neutral。通过形状 customData.tone=primary|success|warning|danger|info|neutral 获取浅底色和对应描边；每页只在类别、状态、主要操作等有意义的位置使用，正文和大面积容器保持中性。用户主动提到的品牌或视觉风格只作为 styleNote 延迟给 draw2code_generate。专业用户回答具体时减少追问，非专业用户模糊时用例子和选项引导。',
  '要点：画板文件是工作区里的 draw2code/<name>.excalidraw.json（用户可在画板工具栏切换/新建多块画板，如 prototype / 顾客端 / 店家端）；画板会把当前选中的名字同步到工作区，Agent 工具省略 name 时必须更新用户当前正在看的画板，只有用户明确点名另一块画板时才传 name。draw2code_list 会返回当前画板。工具 root 参数填会话工作目录。draw2code_update 用 ops 批量 upsert/delete（按 id 幂等），元素坐标为画布像素（y 向下），text 元素需给 text 字段，模块分组用 frame，流程用 arrow（points 相对坐标 [[0,0],[dx,dy]]）。严禁用 Bash、脚本或直接文件写入修改 .excalidraw.json，必须走 draw2code_update，否则无法进行冲突和写入验证。画完原型主动提示用户：可以在右侧画板上直接拖改、删改或补充文案。',
  '生成页面：用户明确说「生成页面 / 生成XX页面 / 根据画板生成前端 / 按最新画板重新生成」时，必须调用 draw2code_generate action=start，不能凭记忆手写，也不能把用户点名的页面直接当成已确认范围。frames 只传用户本次点名的 frame，作为页面多选题的推荐依据；工具始终返回画板全部 frame，必须用宿主 ask_user_question 展示全部 options，让用户直接选择。每个 question 都附带 askUserQuestionArgs，调用宿主时必须原样复制；page-scope 的 multi_select 永远为 true，即使用户只点名了一个页面也禁止改成单选。推荐项已被工具置顶并在 label 中标记“推荐”，description 含原因，不能自行删掉；当前宿主不支持预勾选，因此不要声称推荐项已经选中。随后按 question 继续 action=answer；首次生成只选择一个整体视觉方向，不逐项追问颜色、字体、圆角和技术栈，后续生成默认继承。status=blocked 时先按 blockers 用 draw2code_update 把结构、文案、mock 数据或交互事实补回画板，用户看到并检查后用同一 sessionId/revision 调 action=recheck，禁止重复页面和视觉问题。status=ready 时只展示一次 brief，并立即用宿主 ask_user_question 原样展示 confirmation 的“确认生成 / 修改页面范围 / 修改视觉方向”三个选项，禁止让用户在输入框里手动输入“确认”；选择后分别调用 action=confirm，或 action=revise + 对应 questionId。只有 confirmed 结果才包含 elements 与 instructions，可开始写 draw2code-pages/<board>/index.html。严格生成单文件内联 HTML，只更新所选页面并保留未选页面；参考图只决定视觉表现，内容和流程仍以原型为准。写入文件不等于完成：必须自动打开真实预览，检查所选页面、切换、核心按钮、mock 数据和成功流程，自动修复实现问题并重验；全部通过后如实调用 action=complete，只有返回 status=completed 才能向用户报告完成。中断时 action=resume 从当前阶段继续；普通后续改样式或文案不自动重进 generate，只有用户再次明确要求重新生成才 action=start。',
  '画编辑协作规则：每次 draw2code_update 都应先输出一段“更新摘要”（不是模板化提问）：1) 上一轮用户手工改动；2) 这一轮计划改动；3) 冲突检查（是否触及手工改动或替换/清空）。只有“冲突”时才要求确认，返回 pending 后请只询问相关变更是否覆盖；没冲突则直接执行并汇报结果（不打断用户）。工具返回前会重新读取同一画板验证写入；只有返回 verified=true 且 targetBoard 与 activeBoard 相同，才能说“用户当前画板已画好”；若 verified=true 但两者不同，必须明确说“目标画板已写入、当前界面不可见”，不能声称用户已看到。若检测到手工改动与本轮 upsert/delete 同 id、或执行 clear/replace 且面板非空，就应进入确认流程；确认后重新调用 draw2code_update 并设置 force=true。',
  '限制：单画板 ≤2000 元素、≤512KB；生成前端页面前必须先 draw2code_read 最新画板，不要凭记忆画结构。画板带自动版本存档：你的每次 draw2code_update 都会先快照旧状态（用户可在「历史」菜单回滚任意版本），因此大改不必犹豫。用户提到「画板 / 原型 / 画一下 / draw2code / 画码」时即指本插件，请据此协作。',
].join('\n\n')
