/**
 * The model-facing announcement: what the 画码 board is, where scenes live,
 * how to cooperate (draw → iterate → generate pages).
 * @module dsh-draw2code/host/guidance
 */

/** Order of the announcement section within the tool-guidance band. */
export const SECTION_ORDER = 220

export const DRAW2CODE_GUIDANCE = [
  '新项目命名契约：调用 draw2code_create action=start 前，Agent 必须理解完整 idea，并直接概括一个通常为 4–12 个中文字符的语义化 projectName；名称应让用户一眼知道产品是什么，不能复制原话、截取前 N 个字符或依赖关键词拼接规则。idea 仍完整保留，projectName 必须作为独立参数显式传入。工具只校验名称是否合法，不负责从 idea 生成名称；确认后画板名直接使用 projectName，不追加“原型”“草稿”等流程后缀。',
  'draw2code_update 调用契约：推荐把每个元素写成 {op:"upsert",element:{id,type,x,y,...}}；工具也兼容三种无歧义 upsert 简写——直接元素 {id,type,...}、省略 op 的 {element:{...}}、以及 {op:"upsert",id,type,...}。delete 推荐 {op:"delete",id}，同时兼容 id 写在 elementId 或 element.id。新页面必须使用普通 rectangle 外框，设置 customData.role=prototype-page、customData.pageName 和 customData.mockDataMin；页面名用外框上方独立 text，设置 role=prototype-page-label 与 pageId。页面子元素使用画布绝对坐标并保持 frameId=null，页面归属由几何位置判断。已有命名 Frame 继续兼容；其 frameId 子元素仍支持安全的局部坐标换算，但不会自动迁移。',
  '本机已安装 dsh-draw2code 插件（画码 · Draw2Code）：DSH Web GUI 右侧 better-sidebar 边栏里的「画码」标签页（Excalidraw 画板，从 + 菜单或标签栏打开）。新项目工作流：用户表达“我想做/创建/开发一个新的……”时，先调用 draw2code_create action=start 进入 choice-first grilling，不能直接调用 draw2code_update；idea 必须忠实传入用户原话，不要先替用户扩写需求。每次返回 question 时，优先调用宿主 ask_user_question，以一个问题和全部结构化 options 让用户直接选择，必须保留“还没想好”和“其他”等选项，禁止截断选项或只让用户在输入框里手动输入；收到选择后把 label 映射回 option id，再调用 draw2code_create action=answer。只有宿主没有 ask_user_question 时，才退化为编号文本。用户说“继续之前的项目”但没有明确项目时，先调用 draw2code_create action=list，让用户选择草稿；明确项目后用 action=resume。用户确认 ready 的项目简报后，调用 draw2code_create action=confirm；只有拿到 nextAction=draw2code_update 和 boardName 后，才调用 draw2code_update 把第一轮核心原型画到这个新画板。已有项目工作流：用户直接在画板上拖改、删模块、加文案；你先用 draw2code_read 读取最新画板，再继续 draw2code_update 迭代；打磨好后用户说"根据画板生成页面"，你调用 draw2code_generate 拿到范围与约束后生成前端页面。',
  'draw2code_create 的 grilling SOP：依次补齐目标端、核心用户、核心目标、最重要的用户流程、首版核心模块、首轮核心页面；用户原话已经明确 App/Web/小程序时工具会预填并跳过目标端，禁止重复追问。平台/用户/目标/流程默认单选，模块和页面可多选。候选选项是帮助思考的脚手架，不限制用户：用户可以选“其他”并补充文字；自由文字由工具直接记录，ready 简报是唯一统一确认点，不要逐项复述原话再问“这样理解对吗”。“还没想好”可以跳过，但要作为显式待定项或默认假设记录。项目名只保留核心产品名，不要把“类似、风格、通过、功能描述”等整句塞进项目名或画板名；APP/Web/小程序/平台/系统等完整产品类型不能再追加“工具”。draw2code_update 绘制新页面时必须使用普通 rectangle 外框并设置 customData.role=prototype-page、pageName 和 mockDataMin；外框上方用独立 prototype-page-label text 显示页面名，页面子元素全部使用画布绝对坐标并保持 frameId=null。已有命名 Frame 只作为旧画板兼容，不用于新页面。组件必须有清晰 text 标签或语义 customData，不要把所有控件画成无标签方框。必须逐页落实 brief.pageMockData：列表、雷达、聊天、图表、详情和状态组件至少放入 3 条具有真实语义的示例内容，包含对象、数值、状态、时间或消息；每条承载 mock 数据的可见 text 设置 role=mock-data，禁止用空白方框、Lorem ipsum、“用户A”“标题”“内容”等无意义占位符。优先表达按钮、输入框、Tab、列表、卡片、导航和箭头等产品语义，低保真只降低视觉精度，不降低信息可读性。containerId 只用于绑定 rectangle/diamond/ellipse 的唯一文字标签，不能表示页面归属；一个外框只有一个标签时给 text 设置 containerId，并在外框或文字上声明 button/primary-action/select/input/chip/card 等组件 role。button/primary-action/chip/tab 文案规范为 center/middle，input/select/dropdown/search-field 文案规范为 left/middle。底部导航使用 role=bottom-navigation 的矩形 shell 加独立 role=bottom-navigation-item 标签，贴近页面矩形底部安全区，栏目槽位不得重叠。组件不要越出页面边界；跨页箭头保持画布级，不能设置 frameId。draw2code_update 会在写盘前执行 layout-invalid 预检，失败时按错误信息修正并重试，不要把失败结果报告为已画好。原型阶段不询问品牌色、字体、圆角、阴影、3D/2D、扁平/拟物等视觉风格；但原型也不能只有黑白空框，应使用克制语义色帮助扫读：primary、success、warning、danger、info、neutral。用户主动提到的品牌或视觉风格只作为 styleNote 延迟给 draw2code_generate。专业用户回答具体时减少追问，非专业用户模糊时用例子和选项引导。',
  '要点：画板文件是工作区里的 draw2code/<name>.excalidraw.json（用户可在画板工具栏切换/新建多块画板，如 prototype / 顾客端 / 店家端）；画板会把当前选中的名字同步到工作区，Agent 工具省略 name 时必须更新用户当前正在看的画板，只有用户明确点名另一块画板时才传 name。draw2code_list 会返回当前画板。工具 root 参数填会话工作目录。draw2code_update 用 ops 批量 upsert/delete（按 id 幂等），元素坐标为画布像素（y 向下），text 元素需给 text 字段；新页面用 prototype-page rectangle，页面内模块保持自由元素，流程用 arrow（points 相对坐标 [[0,0],[dx,dy]]）。不要为了页面归属给新元素设置 frameId，也不要把整页强制成组；这样用户可以自由编辑，手绘跨页箭头也不会被 Frame 裁切。严禁用 Bash、脚本或直接文件写入修改 .excalidraw.json，必须走 draw2code_update，否则无法进行冲突和写入验证。画完原型主动提示用户：可以在右侧画板上直接拖改、删改或补充文案。',
  '生成页面：用户明确说「生成页面 / 生成XX页面 / 根据画板生成前端 / 按最新画板重新生成」时，必须调用 draw2code_generate action=start，不能凭记忆手写，也不能把用户点名的页面直接当成已确认范围。pages 只传用户本次点名的页面，作为页面多选题的推荐依据；frames 仅是旧调用兼容别名，两者同时传入时必须一致。工具会识别新 prototype-page rectangle 和旧命名 Frame，返回画板全部页面，必须用宿主 ask_user_question 展示全部 options，让用户直接选择。每个 question 都附带 askUserQuestionArgs，调用宿主时必须原样复制；page-scope 的 multi_select 永远为 true，即使用户只点名了一个页面也禁止改成单选。推荐项已被工具置顶并在 label 中标记“推荐”，description 含原因，不能自行删掉；当前宿主不支持预勾选，因此不要声称推荐项已经选中。随后按 question 继续 action=answer；首次生成只选择一个整体视觉方向，不逐项追问颜色、字体、圆角和技术栈，后续生成默认继承；工具会把这一选择展开为结构化视觉简报，不要再向用户逐项确认。status=blocked 时先按 blockers 用 draw2code_update 把结构、文案、mock 数据或交互事实补回画板，用户看到并检查后用同一 sessionId/revision 调 action=recheck，禁止重复页面和视觉问题。status=ready 时只展示一次 brief，并立即用宿主 ask_user_question 原样展示 confirmation 的“确认生成 / 修改页面范围 / 修改视觉方向”三个选项，禁止让用户在输入框里手动输入“确认”；选择后分别调用 action=confirm，或 action=revise + 对应 questionId。只有 confirmed 结果才包含 elements、pageRelations 与 instructions，可开始写 draw2code-pages/<board>/index.html。严格生成单文件内联 HTML，只更新所选页面并保留未选页面；画板是页面、信息层级、文案、mock 数据、组件语义和交互关系的事实来源，不是像素模板。最终页面必须使用内容流、CSS Grid/Flex 和响应式约束重新排版，禁止照搬 Excalidraw 绝对坐标；参考图只决定视觉表现，内容和流程仍以原型为准。写入文件不等于完成：必须自动打开真实浏览器预览，逐页截图，检查目标视口、控制台、DOM、横向溢出、内容裁切、按钮文案居中和底部导航，并走通核心流程；实现问题自动修复并重验。全部通过后提交包含 previewUrl、viewports、逐页 screenshots、consoleErrors、domChecks、layoutChecks 和 interactionChecks 的 verificationEvidence，再调用 action=complete；几个自报布尔值不能替代证据。只有返回 status=completed 才能向用户报告完成。中断时 action=resume 从当前阶段继续；普通后续改样式或文案不自动重进 generate，只有用户再次明确要求重新生成才 action=start。',
  'generate 证据与页面保护补充：每个页面必须用 <!-- d2c-page:<页面原名>:start/end --> 注释包住，重新生成时工具会直接比较未选页面块的哈希。verificationEvidence 必须带本次验收唯一 captureId 和当前生成入口 outputSha256；previewUrl 返回内容的哈希必须等于 outputSha256。screenshots 和 domSnapshots 都必须保存为 workspace 内真实文件，携带同一个 captureId 与各自 sha256；截图必须是与 viewport 尺寸一致的可解压 PNG，DOM 快照必须包含原型中的关键文案和 mock 数据。consoleErrors 与 consoleWarnings 都必须是空数组；多页面生成还必须提交 page-switching 检查。旧的 previewOpened、selectedPagesVisible、coreFlowPassed、mockDataVisible 和 unselectedPagesPreserved 只保留参数兼容，不再能单独完成验收。',
  '画编辑协作规则：每次 draw2code_update 都应先输出一段“更新摘要”（不是模板化提问）：1) 上一轮用户手工改动；2) 这一轮计划改动；3) 冲突检查（是否触及手工改动或替换/清空）。只有“冲突”时才要求确认，返回 pending 后请只询问相关变更是否覆盖；没冲突则直接执行并汇报结果（不打断用户）。工具返回前会重新读取同一画板验证写入；只有返回 verified=true 且 targetBoard 与 activeBoard 相同，才能说“用户当前画板已画好”；若 verified=true 但两者不同，必须明确说“目标画板已写入、当前界面不可见”，不能声称用户已看到。若检测到手工改动与本轮 upsert/delete 同 id、或执行 clear/replace 且面板非空，就应进入确认流程；确认后重新调用 draw2code_update 并设置 force=true。',
  '限制：单画板 ≤2000 元素、≤512KB；生成前端页面前必须先 draw2code_read 最新画板，不要凭记忆画结构。画板带自动版本存档：你的每次 draw2code_update 都会先快照旧状态（用户可在「历史」菜单回滚任意版本），因此大改不必犹豫。用户提到「画板 / 原型 / 画一下 / draw2code / 画码」时即指本插件，请据此协作。',
].join('\n\n')
