/**
 * The model-facing announcement: what the 画码 board is, where scenes live,
 * how to cooperate (draw → iterate → generate pages).
 * @module dsh-draw2code/host/guidance
 */

import workflowContract from '../references/workflow-contract.md'

/** Order of the announcement section within the tool-guidance band. */
export const SECTION_ORDER = 220

export const DRAW2CODE_GUIDANCE = [
  '新项目命名契约：调用 draw2code_create action=start 前，Agent 必须理解完整 idea，并直接概括一个通常为 4–12 个中文字符的语义化 projectName；名称应让用户一眼知道产品是什么，不能复制原话、截取前 N 个字符或依赖关键词拼接规则。idea 仍完整保留，projectName 必须作为独立参数显式传入。工具只校验名称是否合法，不负责从 idea 生成名称；确认后画板名直接使用 projectName，不追加“原型”“草稿”等流程后缀。',
  'draw2code_update 调用契约：推荐把每个元素写成 {op:"upsert",element:{id,type,x,y,...}}；工具也兼容三种无歧义 upsert 简写——直接元素 {id,type,...}、省略 op 的 {element:{...}}、以及 {op:"upsert",id,type,...}。delete 推荐 {op:"delete",id}，同时兼容 id 写在 elementId 或 element.id。新页面必须使用普通 rectangle 外框，设置 customData.role=prototype-page、customData.pageName 和 customData.mockDataMin；页面名用外框上方独立 text，设置 role=prototype-page-label 与 pageId。页面子元素使用画布绝对坐标并保持 frameId=null，页面归属由几何位置判断。已有命名 Frame 继续兼容；其 frameId 子元素仍支持安全的局部坐标换算，但不会自动迁移。',
  '本机已安装 dsh-draw2code 插件（画码 · Draw2Code）：DSH Web GUI 右侧 better-sidebar 边栏里的「画码」标签页。仅当用户明确说 Draw2Code、画码，或意图明确为“画原型”时进入本工作流；普通编码请求不自动拦截。同一任务首次唤醒后保持 Draw2Code 会话。新项目先调用 draw2code_create action=start，忠实传入 idea 和 Agent 概括的 projectName，禁止直接 draw2code_update。status=discovery 时，先读取 explicitFacts、历史回答、recommendedDimensions 和剩余预算：第一题必须优先从 recommendedDimensions 前两项中选择，不得先问模块、页面或通用信息架构；普通待办先挑战具体触发场景或现有替代，雷达社交先问信任与独特连接机制，穿搭产品先问推荐依据或使用时刻。信息不足就围绕当前最高影响的未知项调用 action=propose_question；question.text 必须直接写成“判断：{insight}\\n\\n问题：{决策问题}”，options 除产品方向外必须显式带上“直接整理项目简报 / 还没想好 / 其他”，否则工具会拒绝，避免 Agent 重组卡片时删掉关键信息。信息足够或用户要求直接整理时调用 action=synthesize。status=question 时用宿主 ask_user_question 原样展示一个问题和全部选项，再 action=answer；用户跳过时调用 action=skip，用户要求直接整理时可直接 action=synthesize。status=ready 时必须完整展示 briefMarkdown，不能压缩成回答摘要；最后再展示一张明确列出全部页面的页面范围确认卡，只提供“确认这些页面并绘制 / 调整页面范围 / 调整产品方向”。用户选择调整时，直接用 action=propose_question 追问受影响的一项，工具会清除旧简报，回答后重新 synthesize 完整简报。确认后 action=confirm，拿到 boardName 才调用 draw2code_update。已有项目先 draw2code_read 再 update；根据画板生成页面时调用 draw2code_generate。',
  'draw2code_create 自适应深挖 SOP：禁止固定依次询问平台、用户、目标、流程、模块和页面，也禁止把模块与页面拆成两道清单题。用户原话已明确的事实不能重复追问。每题必须包含基于当前产品的 insight、一个会改变产品方向的问题、2–4 个有真实取舍的选项、recommendedOptionId、decisionImpact 和 dependsOn；工具自动补充“直接整理项目简报”“还没想好”和“其他”。用户选择 synthesize-now 后立刻 action=synthesize，不能因为原生问题卡片隐藏输入框而继续追问。重点从触发场景、现有替代、核心结果、独特机制、使用闭环、关键风险与首版验证中选择最有价值的一项；简单产品通常 3–5 题，复杂产品最多 10 题。synthesize 必须提交同一份结构化 PrototypeBrief，完整包含产品定义、首版包含与排除范围、页面目标、具体页面结构、每页至少 3 条真实 mock 数据或表单字段、关键状态、页面关系、原型表达原则、验收方式和默认假设；工具据此确定性生成 briefMarkdown、pageBlueprints 与 pageMockData，确认阶段禁止重新推断。原型阶段不询问品牌色、字体、圆角、3D/2D 或技术栈；视觉要求延迟到 generate。draw2code_update 必须完整落实 brief：新页面使用 prototype-page rectangle 与外部标签，子元素 frameId=null；每页只有一个 primary-action，按钮文字 center/middle，底部导航完整贴近安全区，mock 数据首次渲染可见，跨页箭头保持画布级。三个及以上页面必须严格执行 create 返回的 drawingPlan：只为 allowedPageIds 生成代表页 ops，画布可见后用 action=review、reviewToken 和 phase=representative 记录纯复核，再生成 remainingPageIds；禁止预先生成全部页面的大批 ops。最终用 action=review、phase=final 覆盖全部 page id；writeVerified 不等于完成。',
  '要点：画板文件是工作区里的 draw2code/<name>.excalidraw.json（用户可在画板工具栏切换/新建多块画板，如 prototype / 顾客端 / 店家端）；画板会把当前选中的名字同步到工作区，Agent 工具省略 name 时必须更新用户当前正在看的画板，只有用户明确点名另一块画板时才传 name。draw2code_list 会返回当前画板。工具 root 参数填会话工作目录。draw2code_update 用 ops 批量 upsert/delete（按 id 幂等），元素坐标为画布像素（y 向下），text 元素需给 text 字段；新页面用 prototype-page rectangle，页面内模块保持自由元素，流程用 arrow（points 相对坐标 [[0,0],[dx,dy]]）。不要为了页面归属给新元素设置 frameId，也不要把整页强制成组；这样用户可以自由编辑，手绘跨页箭头也不会被 Frame 裁切。严禁用 Bash、脚本或直接文件写入修改 .excalidraw.json，必须走 draw2code_update，否则无法进行冲突和写入验证。画完原型主动提示用户：可以在右侧画板上直接拖改、删改或补充文案。',
  '生成页面：用户明确说「生成页面 / 生成XX页面 / 根据画板生成前端 / 按最新画板重新生成」时，先用普通对话问一次“有没有参考风格的图片？有的话直接发图，没有也可以由我智能推荐”；这句话不使用 ask_user_question。用户已经随请求附图时不要重复问；查看图片后把视觉摘要或路径作为 referenceStyle 传入，没有则传 none。然后必须调用 draw2code_generate action=start，不能凭记忆手写，也不能把用户点名的页面直接当成已确认范围。工具缺少 referenceStyle 时会返回 reference-style-prompt 且不创建会话。pages 只传用户本次点名的页面，作为页面多选题的推荐依据；frames 仅是旧调用兼容别名，两者同时传入时必须一致。工具会识别新 prototype-page rectangle 和旧命名 Frame，返回画板全部页面，必须用宿主 ask_user_question 展示全部 options，让用户直接选择。每个 question 都附带 askUserQuestionArgs，调用宿主时必须原样复制；page-scope 的 multi_select 永远为 true，即使用户只点名了一个页面也禁止改成单选。推荐项已被工具置顶并在 label 中标记“推荐”，description 含原因，不能自行删掉；当前宿主不支持预勾选，因此不要声称推荐项已经选中。随后按 question 继续 action=answer；有参考图时视觉方向题优先推荐沿用参考图，没有时根据产品语义智能推荐。首次生成只选择一个整体视觉方向，不逐项追问颜色、字体、圆角和技术栈，后续生成默认继承；工具会把这一选择展开为结构化视觉简报，不要再向用户逐项确认。status=blocked 时先按 blockers 用 draw2code_update 把结构、文案、mock 数据或交互事实补回画板，用户看到并检查后用同一 sessionId/revision 调 action=recheck，禁止重复页面和视觉问题。status=ready 时只展示一次 brief，并立即用宿主 ask_user_question 原样展示 confirmation 的“确认生成 / 修改页面范围 / 修改视觉方向”三个选项，禁止让用户在输入框里手动输入“确认”；选择后分别调用 action=confirm，或 action=revise + 对应 questionId。只有 confirmed 结果才包含 elements、pageRelations 与 instructions，可开始写 draw2code-pages/<board>/index.html。严格生成单文件内联 HTML，只更新所选页面并保留未选页面；画板是页面、信息层级、文案、mock 数据、组件语义和交互关系的事实来源，不是像素模板。最终页面必须使用内容流、CSS Grid/Flex 和响应式约束重新排版，禁止照搬 Excalidraw 绝对坐标；参考图只决定视觉表现，内容和流程仍以原型为准。写入文件不等于完成：必须自动打开真实浏览器预览，逐页截图，检查目标视口、控制台、DOM、横向溢出、内容裁切、按钮文案居中和底部导航，并走通核心流程；实现问题自动修复并重验。全部通过后提交包含 previewUrl、viewports、逐页 screenshots、consoleErrors、domChecks、layoutChecks 和 interactionChecks 的 verificationEvidence，再调用 action=complete；几个自报布尔值不能替代证据。只有返回 status=completed 才能向用户报告完成。中断时 action=resume 从当前阶段继续；普通后续改样式或文案不自动重进 generate，只有用户再次明确要求重新生成才 action=start。',
  'generate 证据与页面保护补充：每个页面必须用 <!-- d2c-page:<页面原名>:start/end --> 注释包住，重新生成时工具会直接比较未选页面块的哈希。verificationEvidence 必须带本次验收唯一 captureId 和当前生成入口 outputSha256；previewUrl 返回内容的哈希必须等于 outputSha256。screenshots 和 domSnapshots 都必须保存为 workspace 内真实文件，携带同一个 captureId 与各自 sha256；截图必须是与 viewport 尺寸一致的可解压 PNG，DOM 快照必须包含原型中的关键文案和 mock 数据。consoleErrors 与 consoleWarnings 都必须是空数组；多页面生成还必须提交 page-switching 检查。旧的 previewOpened、selectedPagesVisible、coreFlowPassed、mockDataVisible 和 unselectedPagesPreserved 只保留参数兼容，不再能单独完成验收。',
  '画编辑协作规则：已有项目先调用一次 draw2code_read，并直接读取 continuation 与 capacity，禁止搜索会话历史来找 reviewToken 或 pendingUpdateId。只有当前任务确实是在恢复同一批暂存写入时，才执行 continuation.nextAction；新的独立小改动直接按最新画板生成最小 ops，已有 3 页以上的成熟画板不会被旧的首次代表页门禁拦截。每次 draw2code_update action=write 都应先输出一段“更新摘要”（不是模板化提问）：1) 上一轮用户手工改动；2) 这一轮计划改动；3) 冲突检查（是否触及手工改动或替换/清空）。只有“冲突”时才要求确认，返回 pending 后请只询问相关变更是否覆盖；没冲突则直接执行并汇报结果（不打断用户）。写入成功会选中目标画板、发布 reveal request 并返回不透明 reviewToken；Canvas 实际可见后用 action=review 单独复核，review 不传 ops、不改变 revision、不发布新 reveal，并按 nextActionCode 继续。若 Agent 误在代表页复核前提交了其余页面，工具会返回 pendingUpdateId 并保留该批 ops；复核后使用 action=commit_pending 和该 ID 提交，禁止重新生成或重传大 JSON。旧 visualReview 仅为兼容，新的调用不要手工拼 boardRevision/revealRequestId。verified=true / writeVerified=true 只证明写盘和回读一致，不等于原型完成；只有 final review 返回 completionReady=true 才能说整套原型已经完成。prototypeQuality.warnings 要作为下一轮打磨依据，不能被 verified 掩盖。若检测到手工改动与本轮 upsert/delete 同 id、或执行 clear/replace 且面板非空，就应进入确认流程；确认后重新调用 draw2code_update 并设置 force=true。',
  '限制：单画板 ≤2000 元素、≤512KB；draw2code_read / draw2code_open 会返回精确 usedBytes、remainingBytes 和 continuation。生成大批 ops 前先看 remainingBytes；若 update 返回 nextActionCode=reduce_update_scope，按 nextActionParams 拆成更小的独立批次，不要重复生成原批 JSON。update.timings 只统计工具内部读盘、预检、写盘、回读验证和发布阶段，不包含工具调用前的 Agent 推理时间。生成前端页面前必须先 draw2code_read 最新画板，不要凭记忆画结构。画板带自动版本存档：你的每次 draw2code_update 都会先快照旧状态（用户可在「历史」菜单回滚任意版本），因此大改不必犹豫。只有明确的 Draw2Code / 画码 / 画原型唤醒本插件；唤醒后的同一任务里，画板、原型、画一下等后续说法继续沿用本工作流。',
  workflowContract,
].join('\n\n')
